name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # write 才能发布 Release
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.7'

      # 给 gradlew 赋予执行权限，防止在 Linux 环境下报错
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      # 从 gradle.properties 中提取插件名称和版本号
      - name: Get Plugin Version
        id: plugin_info
        run: |
          VERSION=$(grep 'pluginVersion' gradle.properties | cut -d'=' -f2 | xargs)
          TAG_VERSION=$(grep 'pluginTagVersion' gradle.properties | cut -d'=' -f2 | xargs)
          NAME=$(grep 'pluginName' gradle.properties | cut -d'=' -f2 | xargs)
          echo "full_name=${NAME}-${VERSION}" >> $GITHUB_OUTPUT

      # 构建 IntelliJ 插件
      - name: Build Plugin with Gradle
        run: ./gradlew buildPlugin

      # 发布到 Releases
      - name: Release Plugin
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/master'
        with:
          # 创建 github 的标签用于发布到 release，如 v2.2.8
          tag_name: v${{ steps.plugin_info.outputs.tag_version }}
          name: v${{ steps.plugin_info.outputs.tag_version }}
          generate_release_notes: true # 自动根据提交记录写说明
          files: build/distributions/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.plugin_info.outputs.full_name }}
          # IDEA 插件打包后的 zip 文件默认存放在 build/distributions/
          path: build/distributions/*.zip

  # 依赖提交
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
